### ISSUE TITLE
Question of understanding: Isn't the serial number for itself sufficient when verifying it?

### ISSUE THREAD

**Issue by eidenschink** [cubiclesoft/php-license-server#4]
Hi CubicleSoft!

I'm working my way into your very nice project and stumbled accross the following thing I need to understand:
 
I created a license with `LicenseServer::CreateLicense($productid, $majorver, $userinfo, $options = array())` and used a `$_SERVER["HTTP_HOST"]` (in the license requesting client) as my value for `$userinfo` (as for registering websites in my demo project).

My question is: When I now have a serial number and try to verify it using `LicenseServer::VerifySerial($serialnum, $productid, $majorver, $userinfo, $mode = false, $log = false)` or more specific: `LicenseServer::VerifySerial($serialnum, $productid, $majorver, $userinfo)` the `$userinfo` is not optional. 

I thought serial numbers are unique? Would it be possible to make verification of serial numbers without `$userinfo`?

If not and say in situations where you don't have (or want to use it because it might change, as in my use case the requesting clients might have changed their domain from www.example.com to example.com) the extra `$userinfo` one would use `GetLicenses` and loop over all created licenses (revoked, expired, active...) to search for the serial number.

Please excuse if I have a fundamental misunderstanding here.

**Comment by eidenschink** [comment]
I withdraw my question as I know now what confused me and what options have an effect on the serial number.

**Comment by cubiclesoft** [comment]
Serial numbers generated by the functions are encrypted data blobs.  As per the comments in the source code for `serial_number.php`:

```
			// Format of each key (big-endian, 10 bytes):
			//
			//  1 bit:   Expires - affects Date field (0 = No, 1 = Yes)
			// 20 bits:  Date issued or expires ((int)(UNIX timestamp / 86400), ~2873 years)
			// 10 bits:  Product ID (0-1023)
			//  4 bits:  Product classification (e.g. 0 = Standard, 1 = Pro, 2 = Enterprise)
			//  8 bits:  Major version (0-255)
			//  8 bits:  Minor version (0-255)
			//  5 bits:  Custom bits per app (e.g. flags)
			// 24 bits:  Start of HMAC SHA-1 of the first 56 bits (7 bytes) of this serial '|' user-specific info (e.g. email).
```

Here's an entire article on the topic of designing a serial number.  It's an interesting read:

https://cubicspot.blogspot.com/2020/03/adventuring-deeply-into-software-serial.html

I believe for your situation of restricting a license to a specific top-level domain (TLD), parsing an incoming string and removing any subdomain portions would allow you to get something close to the TLD.

Note that `HTTP_HOST` can be spoofed, can contain a port number, or might not even exist.  It's the raw incoming `Host` header from the web client (not necessarily a web browser).  When a web server can't figure out which virtual host to use, it falls back to a configured "default server."  So the `Host` header could even contain garbage that isn't a valid domain name.

Glad to hear you got it figured out though.

**Comment by eidenschink** [comment]
Hi! Thanks for your detailed answer. In my use case a manual check of the supplied data will be applied. Using data that can be spoofed is only done while I'm getting to know the tool better.

I read your blog post today, it's very comprehensive. Thanks! 👍
