### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by GabrielOnDelphi** [cubiclesoft/php-license-server#5]
I looked everywhere and I could not find under which license are your projects released. 
Your website mention the work "license" once but there is no link to it in sight.
Probably an oversight  :)

Is this project released under MIT or Apache?

Thanks for posting the nice project!

**Comment by cubiclesoft** [comment]
It's listed under "Features" in the readme:

> Has a liberal open source license.  MIT or LGPL, your choice.

You can choose which of those two licenses to license the software under.  Most people will select MIT for its permissiveness, but LGPL is generally better for GPL-compatible licenses/software.  GitHub's license detection mechanism is not actually capable of handling licensing under multiple open source licenses.  Also, there's no actual legal need to clone the text of well-known licenses for the gazillionth time.

By the way, I'm currently sitting on _major_ changes to this particular project.  The changes are fully compatible with the software that's currently here but there are a bunch of important features I needed to add to support my current use case.  My GitHub activity log has been very quiet for the past couple of years as I've been working on a major project.  Once I'm done with that project, I will ready a series of updates to push out across multiple projects.  Something you can look forward to anyway in the coming months.

Glad to hear that you are finding this project useful.
